//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Id { get; set; }
        public string Message1 { get; set; }
        public int AuthorId { get; set; }
        public Nullable<System.Guid> ConversationId { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
