//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInConversation
    {
        public System.Guid Id { get; set; }
        public System.Guid ConversationId { get; set; }
        public int UserId { get; set; }
    
        public virtual Conversation Conversation { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
