//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChat.Domain.Models.EntityClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Conversations = new HashSet<Conversation>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Nickname { get; set; }
    
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
