//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveChat.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public Conversation()
        {
            this.Messages = new HashSet<Message>();
            this.UserProfiles = new HashSet<UserProfile>();
        }
    
        public System.Guid Id { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
    }
}
